apiVersion: v1
kind: PersistentVolume
metadata:
  name: joplin-data-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/external-hdd/joplin/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: joplin-data-pvc
  namespace: joplin
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
