apiVersion: v1
kind: PersistentVolume
metadata:
  name: memos-data-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/external-hdd/memos/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: memos-data-pvc
  namespace: memos
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
